"""
Shared helpers for the storytelling dashboard.

Keep this module light: no torch / predict_latest imports here, so every
story page loads fast. Only app_pages/09_live.py imports the heavy stack.
"""
import json
from pathlib import Path

import numpy as np
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt

# ---------- paths ----------
ROOT = Path(__file__).parent
MODELS_DIR = ROOT / "models"
FIG_MODELS = ROOT / "figures" / "models"
FIG_EDA = ROOT / "figures" / "eda"
FIG_FEATURES = ROOT / "figures" / "features"
MASTER_CSV = ROOT / "data" / "interim" / "fx_master_dataset.csv"
FEATURES_CSV = ROOT / "data" / "processed" / "fx_features.csv"
LIVE_CSV = ROOT / "data" / "processed" / "fx_features_live.csv"

# ---------- colors ----------
DARK_BG = "#161b26"
C_DL, C_DL2 = "#ffb400", "#c78c00"     # amber  = deep learning
C_ML, C_ML2 = "#4f8df5", "#31589c"     # blue   = machine learning
C_BASE = "#ff6b6b"                     # baseline lines
C_GRAY = "#8892a6"

plt.rcParams.update({
    "figure.facecolor": DARK_BG,
    "axes.facecolor":   DARK_BG,
    "savefig.facecolor": DARK_BG,
    "text.color":       "#e6e9ef",
    "axes.labelcolor":  "#aab2c0",
    "xtick.color":      "#aab2c0",
    "ytick.color":      "#aab2c0",
    "axes.edgecolor":   "#3d4656",
    "grid.color":       "#2a3140",
    "legend.facecolor": DARK_BG,
    "legend.edgecolor": "#3d4656",
    # cleaner, more modern axes: no boxed frame, soft horizontal grid only
    "axes.spines.top":    False,
    "axes.spines.right":  False,
    "axes.spines.left":   False,
    "axes.grid":          True,
    "axes.grid.axis":     "y",
    "grid.linewidth":     0.6,
    "grid.alpha":         0.5,
    "axes.axisbelow":     True,
    "axes.titlesize":     11,
    "axes.titleweight":   "bold",
    "axes.titlecolor":    "#e6e9ef",
    "axes.labelsize":     9,
    "xtick.labelsize":    9,
    "ytick.labelsize":    9,
    "legend.frameon":     False,
})

# ---------- project identity ----------
PROJECT_TITLE = "Forecasting Foreign Exchange Rates Using Machine Learning Techniques"
PROJECT_SUBTITLE = ("A EUR/USD case study — direction and volatility with "
                    "machine learning and deep learning, under the "
                    "Efficient Market Hypothesis")
AUTHOR = "Dong Cong Gia Khang"
COURSE = "Final Project · FPT Greenwich · 2026"

# ---------- result highlight colors (for pandas Styler) ----------
GREEN_BG = "background-color: rgba(46, 160, 67, 0.28)"    # beats baseline
RED_BG = "background-color: rgba(248, 81, 73, 0.24)"       # below baseline
AMBER_BG = "background-color: rgba(255, 180, 0, 0.22); font-weight: 700"

# ---------- key numbers, all produced by the notebooks (NB05-NB09) ----------
VOL_HORIZON = 5                     # the regression predicts a 5-day average
VOL_VMAX = 0.015528                 # min-max scale of the volatility target
BASE_DIR_DAILY = 51.21              # majority-class baseline, val, daily
BASE_DIR_WEEKLY = 52.54             # majority-class baseline, val, weekly
BASE_VOL_CLF = 55.45                # majority-class baseline, val
BASE_VOL_MAE_MEAN = 0.0972          # always predict the train MEAN
BASE_VOL_MAE_MEDIAN = 0.0897        # always predict the train MEDIAN (right
BASE_VOL_MAE = BASE_VOL_MAE_MEDIAN  # reference for MAE, so this is the one)
LIT_CEILING = 58.52                 # Guyard & Deriaz 2024, 21 algorithms
RENAISSANCE = 50.75                 # Renaissance Technologies win rate

# Split used to train the models: a strictly chronological 70 / 20 / 10
# split by row position. These dates are the calendar boundaries those row
# fractions land on. Everything is regenerated by re-running the notebooks.
TRAIN_END = "2021-08-13"
VAL_END = "2024-11-25"


# ---------- cached loaders ----------
# Every loader takes a `stamp` argument built from the files' modification
# times. Streamlit keys its cache on the arguments, so retraining a model
# changes the stamp and the page picks up the new numbers on the next run.
# Without this the app keeps serving whatever it read when it started.
def _stamp(*paths):
    return tuple(p.stat().st_mtime_ns if p.exists() else 0 for p in paths)


@st.cache_data
def _load_master(stamp):
    if not MASTER_CSV.exists():
        return None
    df = pd.read_csv(MASTER_CSV, parse_dates=["date"])
    return df.dropna(subset=["eurusd"]).reset_index(drop=True)


def load_master():
    return _load_master(_stamp(MASTER_CSV))


@st.cache_data
def _load_features_frozen(stamp):
    if not FEATURES_CSV.exists():
        return None
    return pd.read_csv(FEATURES_CSV, parse_dates=["date"])


def load_features_frozen():
    return _load_features_frozen(_stamp(FEATURES_CSV))


RESULT_CSVS = ["all_10_models_comparison.csv",
               "volatility_regression_results.csv",
               "volatility_classification_results.csv"]

# The naive rule the price forecaster is measured against, spelled the same way
# notebook 09 writes it into price_forecast_accuracy.csv.
NAIVE_PRICE = "Naive (today's price)"


@st.cache_data
def _load_price(stamp):
    """Accuracy-by-tolerance table + champion name, from notebook 09."""
    p = MODELS_DIR / "price_forecast_accuracy.csv"
    if not p.exists():
        return None
    acc = pd.read_csv(p)
    meta_p = MODELS_DIR / "price_meta.json"
    best = None
    if meta_p.exists():
        best = json.load(open(meta_p)).get("best_model")
    if best is None:                       # derive it the way the notebook does
        best = (acc[acc["tol_pip"].isin([50, 55, 60])]
                .groupby("model")["val"].mean().idxmax())
    return {"acc": acc, "best": best}


def load_price():
    return _load_price(_stamp(MODELS_DIR / "price_forecast_accuracy.csv",
                              MODELS_DIR / "price_meta.json"))


@st.cache_data
def _load_interval(stamp):
    """Calibrated-interval coverage: claimed confidence vs what happened."""
    p = MODELS_DIR / "price_interval_coverage.csv"
    return pd.read_csv(p) if p.exists() else None


def load_interval():
    return _load_interval(_stamp(MODELS_DIR / "price_interval_coverage.csv"))


def load_results():
    return _load_results(_stamp(*[MODELS_DIR / f for f in RESULT_CSVS]))


@st.cache_data
def _load_results(stamp):
    data = {}
    p = MODELS_DIR / "all_10_models_comparison.csv"
    if p.exists():
        d = pd.read_csv(p, index_col=0)
        d.columns = [c.strip().lower() for c in d.columns]
        data["direction"] = d
    p = MODELS_DIR / "volatility_regression_results.csv"
    if p.exists():
        data["vol_reg"] = pd.read_csv(p, index_col=0)
    p = MODELS_DIR / "volatility_classification_results.csv"
    if p.exists():
        data["vol_clf"] = pd.read_csv(p, index_col=0)
    return data


# ---------- UI helpers ----------
def fig_card(path, what, why, title=None):
    """A figure with its explanation: what the chart shows, why it matters."""
    with st.container(border=True):
        if title:
            st.markdown(f"#### :orange[{title}]")
        if path.exists():
            st.image(str(path), width="stretch")
        else:
            st.error(f"Figure not found: {path.name}")
        st.markdown(f":blue-badge[:material/visibility: What you are "
                    f"looking at]&nbsp; {what}")
        st.markdown(f":green-badge[:material/lightbulb: Why it matters]"
                    f"&nbsp; {why}")


def next_chapter(page_path: str, label: str):
    st.markdown("")
    st.page_link(page_path, label=f"Next: {label}",
                 icon=":material/arrow_forward:")


def verdict(ok: bool, win_text: str, lose_text: str) -> str:
    """Return a colored badge string for a good/bad outcome."""
    if ok:
        return f":green-badge[:material/check_circle: {win_text}]"
    return f":red-badge[:material/cancel: {lose_text}]"


def hl_vs_baseline(col, baseline, higher_is_better=True):
    """Styler helper: green if the value beats the baseline, red if not."""
    out = []
    for v in col:
        try:
            better = (v >= baseline) if higher_is_better else (v <= baseline)
        except TypeError:
            out.append("")
            continue
        out.append(GREEN_BG if better else RED_BG)
    return out


GRAPH_STYLE = """
    bgcolor="transparent";
    rankdir=LR;
    node [style="filled", fillcolor="#232a3a", fontcolor="#e6e9ef",
          color="#3d4656", fontname="Helvetica", fontsize=11, shape=box];
    edge [color="#8892a6", fontcolor="#aab2c0", fontname="Helvetica",
          fontsize=9];
"""
